### ISSUE TITLE
Integration Endpoint

### ISSUE THREAD

**Issue by ratsclub** [mataroablog/mataroa#16]
Hello,

It would be nice to have some kind of integration that would allow one to publish post from the CLI or a CI job. 

I feel that exploring this would make it easier for people to have their blog posts on a Git repository and still publish them to mataroa. What do you think about it?

**Comment by sirodoht** [comment]
Hi @ratsclub,

That's a great idea, I feel, as well.

Would you imagine it being an API endpoint, accepting the blog post as POST body? Or something else?

**Comment by ratsclub** [comment]
Exactly! I feel that a POST and a PATCH form should be enough for this. 

POST for new entries and PATCH to update older entries. What do you think about it?

**Comment by sirodoht** [comment]
Just (c6e2154817b55a9bd434ae599dc62dd5c45866ec) deployed a first iteration of the API. Currently one can only create a new blog post.

Let me know what you think!

**Comment by ratsclub** [comment]
Awesome work! Exactly what I imagined!

**Comment by sirodoht** [comment]
Complete API docs at https://mataroa.blog/api/docs/
