### ISSUE TITLE
question about API: is it possible to allow cors?

### ISSUE THREAD

**Issue by RetricSu** [mataroablog/mataroa#24]

**Comment by sirodoht** [comment]
Hey @RetricSu!

Just to make the request clearer, is this about doing requests in the Mataroa API from a client-side JavaScript script?

**Comment by RetricSu** [comment]
> Hey @RetricSu!
> 
> Just to make the request clearer, is this about doing requests in the Mataroa API from a client-side JavaScript script?

yes exactly, just wondering if that is possible

**Comment by RetricSu** [comment]
given that using API requires Authorization Header, it might be a bad idea to allow cors.

**Comment by truenicoco** [comment]
Wouldn't it be OK to allow CORS for the RSS feeds (blog posts and comments) though?
