### ISSUE TITLE
Standard theme font has changed from sans-serif to serif

### ISSUE THREAD

**Issue by sesh** [mataroablog/mataroa#25]
A recent change has changed the look and feel for the standard theme.

Checking in to see if this was intentional or not?

A quick bisect indicates this issue was introduced in this commit:
[d85bd951390ab28a1b3482378e87dc51368ad516] move style into asset templates

Current rendering for me:
![Example blog post with serif font and larger font size](https://user-images.githubusercontent.com/59980/170820619-a368b677-9d19-425e-9029-5c64dc03f180.png)

Previous design:
![Example blog post with sans-serif font and slightly smaller size](https://user-images.githubusercontent.com/59980/170820622-b03d7012-ccd6-4b40-a195-52e82d542e70.png)

**Comment by sirodoht** [comment]
Hi @sesh! Yes, this was an intentional change.

What do you think about it?

**Comment by sesh** [comment]
It's quite abrupt.

When I jumped online to share a post on Saturday morning my immediate thought was that some CSS had failed to load. The "Times New Roman" in your face look wasn't what I was expecting.

The old theme appealed to me in a bunch of ways. Perhaps a change like this is something that could be an option, or a different theme folks can choose (though, I realise that goes against some of your core goals). I'm sure I'll eventually come around to it but my initial reaction was that something was broken – perhaps not what you were aiming for.

**Comment by sirodoht** [comment]
Hey @sesh,

1. I have introduced a 'Theme Sans-serif' option in settings, which will revert the previous look.

2. I agree in not liking Times New Roman. I want to popularise the idea of people choosing their own fonts from their browser settings. I've been tweaking my own for a few months now and I enjoy looking my choice in the few websites that don't define a font (mataroa included) :D
Here's how you can do that in Firefox & Chrome:
https://support.mozilla.org/en-US/kb/change-fonts-and-colors-websites-use
https://www.ghacks.net/2017/02/24/advanced-font-settings-for-google-chrome/

**Comment by yffr** [comment]
this is a little unrelated, but will there be opportunities to add other CSS and theming customization? i appreciate the optional email notifications but would love an option to disable the RSS option and customize link colors. if not, no problem - thanks for the work put into this project thus far, it's fantastic

**Comment by sirodoht** [comment]
Hey @yffr!

We had a similar discussion at #3.

Essentially, there are no plans to enable users to add custom CSS because that would mean that they would have to spend time deciding what style they want their blog to have. This is in contrast to our philosophy, which is very narrow.

However, one can add a few allowed inline CSS styles (a limited set [here](https://github.com/mataroa-blog/mataroa/blob/ce550248ac8bc4ea7fbae22c7773350975b141ec/main/denylist.py#L170-L184)), for example, when one makes a table and want to make everything fit in one line.

**Comment by sesh** [comment]
Closing this because it was an intentional change, and additional themes have been added.

Feel free to re-open it if you wanted to keep it around for some other reason.
