### ISSUE TITLE
is Mataroa Blog extendable?

### ISSUE THREAD

**Issue by digi-monkey** [mataroablog/mataroa#26]
Hi, love your idea for simplicity and minimalism. I really enjoy the naked blog. I am wondering if mataroa is extendable as well, say I want to add some custom js/html components, load some external script tag, is this kind of thing possible on mataroa?

**Comment by sirodoht** [comment]
Hi @digi-monkey,

Glad you like mataroa.blog!

To answer your question, no, these functionalities are not possible. Mataroa is not designed to be extendable. We want it to be as limiting as possible, actually :D

**Comment by digi-monkey** [comment]
thanks, good to know that.
