### ISSUE TITLE
Migrate mata to mataroa-blog organization

### ISSUE THREAD

**Issue by ratsclub** [mataroablog/mataroa#30]
Hello, I've just refactored a huge chunk of [mata](https://github.com/vtrf/mata) and it should be way easier to maintain and add new features now!

I was also thinking if perhaps you could integrate the repo on the mataroa's organization? I guess it would get a lot more attention there and be actually used!

If something worries you like licensing, project name or any other thing, I have no problem adjusting it to fit the organization as I just want people to use it 😄

**Comment by sirodoht** [comment]
Hey, this sounds like a great idea!

**Comment by ratsclub** [comment]
You can find it here now: https://github.com/mataroa-blog/mata. Do you think we should call it mataroa-cli instead? I guess it would make more sense.


Thanks, @sirodoht!

**Comment by sirodoht** [comment]
Hmm yeah, that might be a good idea. Potentially also change the binary name to just `mataroa`? Or maybe `mata` is nicer because it's shorter?

**Comment by ratsclub** [comment]
I named it `mata` because it's shorter, it's easier to type. I have no problem with the name `mataroa` on the command-line though.

However I was mostly talking about the repo name, `mata` is too vague so I guess `mataroa-cli` would be clearer to the people seeing the repo.

**Comment by sirodoht** [comment]
Sounds good! Let’s change it.

**Comment by ratsclub** [comment]
~I don't have the permissions to rename the repo. May you do it when you have time? Thanks!~

Done, thanks!
