### ISSUE TITLE
python manage.py loaddata dev-data

### ISSUE THREAD

**Issue by Danielovich** [mataroablog/mataroa#57]
Running on a windows box, but I am getting this error when running python manage.py loaddata dev-data.

The error occurs from pk=11 to pk=15
...
  {
    "model": "contenttypes.contenttype",
    "pk": 15,
    "fields": {
      "app_label": "sessions",
      "model": "session"
    }
  },
...
django.db.utils.IntegrityError: Problem installing fixture 'C:\Code\mataroa\main\fixtures\dev-data.json': Could not load contenttypes.ContentType(pk=15): duplicate key value violates unique constraint "django_content_type_app_label_model_76bd3d3b_uniq"
DETAIL:  Key (app_label, model)=(sessions, session) already exists.

**Comment by sirodoht** [comment]
Hey! Thanks for reporting this. I've made some change, could you verify if it's solved?

**Comment by Danielovich** [comment]
Sorry for the long delay here. I am up and running and it has taken a while for me to get it going. But I simply deleted those items in the json file.
