### ISSUE TITLE
Proposal: Change license to Affero GPL 3.0-only

### ISSUE THREAD

**Issue by sirodoht** [mataroablog/mataroa#63]
I want to change the license of this repository (https://github.com/mataroa-blog/mataroa) and its code to be under the terms of GNU Affero General Public License version 3.0 only.

The most significant difference with this change is that whoever wants to distribute the mataroa software will have to disclose their changes to the source code, if any. In contrast, our current MIT license allows one to take this software and distribute it as closed source.

To make this change, all contributors must agree to relicense their contributions under the new license, GNU Affero General Public License version 3.0 only.

If you are a contributor and agree with this license change, please comment below. This is the complete list of contributors who need to agree, as of 2024-06-30 17:00 UTC+0, according to the [GitHub Contributors page](https://github.com/mataroa-blog/mataroa/graphs/contributors):

* @sirodoht 
* @merlinscholz 
* @ratsclub 
* @geoah 
* @xplosionmind 
* @knutwalker 
* @Unknowing9428 
* @pratul 
* @bpevs 
* @geokeloglou 

The full AGPL-3.0-only license text is here: https://spdx.org/licenses/AGPL-3.0-only.html

Here are summaries of the two licenses from TLDRLegal:

* https://www.tldrlegal.com/license/gnu-affero-general-public-license-v3-agpl-3-0
* https://www.tldrlegal.com/license/mit-license

**Comment by sirodoht** [comment]
I agree with the license change of the mataroa codebase (https://github.com/mataroa-blog/mataroa) to GNU Affero General Public License version 3.0 only.

**Comment by knutwalker** [comment]
I agree with the license change

**Comment by geoah** [comment]
I agree with the license change

**Comment by bpevs** [comment]
haha does my change even count as a contribution? 😆 
But I mean sure I agree with the license change.

**Comment by ghost** [comment]
I agree with the license change

**Comment by geokeloglou** [comment]
I agree with the license change of the mataroa [codebase](https://github.com/mataroa-blog/mataroa) to GNU Affero General Public License version 3.0 only.

**Comment by ghost** [comment]
Agreed. Thank you Theodore!

**Comment by pratul** [comment]
I agree with this license change! Thank you for building mataroa.

**Comment by xplosionmind** [comment]
Humbled to be considered a contributor 😍
I agree!

**Comment by xplosionmind** [comment]
Humbled to be considered a contributor 😍
I agree and I applaud this choice!

**Comment by ratsclub** [comment]
I agree with the license change of the mataroa codebase (https://github.com/mataroa-blog/mataroa) to GNU Affero General Public License version 3.0 only.—Victor FreireOn 30 Jun 2024, at 13:50, Theodore Keloglou ***@***.***> wrote:﻿
I want to change the license of this repository (https://github.com/mataroa-blog/mataroa) and its code to be under the terms of GNU Affero General Public License version 3.0 only.
The most significant difference with this change is that whoever wants to distribute the mataroa software will have to disclose their changes to the source code, if any. In contrast, our current MIT license allows one to take this software and distribute it as closed source.
To make this change, all contributors must agree to relicense their contributions under the new license, GNU Affero General Public License version 3.0 only.
If you are a contributor and agree with this license change, please comment below. This is the complete list of contributors as of 2024-06-30 according to the GitHub Contributors page:

@sirodoht
@merlinscholz
@ratsclub
@geoah
@xplosionmind
@knutwalker
@Unknowing9428
@pratul
@bpevs
@geokeloglou

The full AGPL-3.0-only license text is here: https://spdx.org/licenses/AGPL-3.0-only.html
Here are summaries of the two licenses from TLDRLegal:

https://www.tldrlegal.com/license/gnu-affero-general-public-license-v3-agpl-3-0
https://www.tldrlegal.com/license/mit-license

**Comment by sirodoht** [comment]
Great! Thanks everybody! It's done: https://github.com/mataroa-blog/mataroa/commit/c6b8e9e2df9265c506847caebb583cc2b5354ac8
