### ISSUE TITLE
Able to exclude `body` from `GET /api/posts/`

### ISSUE THREAD

**Issue by imcotton** [mataroablog/mataroa#86]
Sometime I only need the metadata of posts and only to expand get the whole body via `/api/posts/<slug>/`.

Maybe something like `/api/posts/?nobody=1` that not resulting as DB dump?

_or_

`/api/posts-meta/`

**Comment by sirodoht** [comment]
Hey @imcotton !

Sorry I didn't get back to you earlier. That would be cool to have! Might to in the future at some point, but feel free to open a PR if you want :)

**Comment by imcotton** [comment]
Good to know that this idea was not rejected from the beginning. Sorry, I'm not familiar with Python in this context. Since this is not urgent, I'll keep an eye on it once it's implemented in the future. Thanks.
